server:
  port: 8761
spring:
  application:
    name: spring-cloud-eureka-server
eureka:
  client:
    fetch-registry: false
    register-with-eureka: false
logging:
  level:
    org:
      springframework:
        web: DEBUG
        ws:
          client:
            MessageTracing:
              received: TRACE
              sent: DEBUG
          server:
            MessageTracing:
              received: TRACE
              sent: DEBUG 